# Generated by Django 3.2.9 on 2022-11-23 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
