# Generated by Django 5.2 on 2026-07-27 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_product_orderitem_item"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.RemoveField(
            model_name="order",
            name="created",
        ),
        migrations.RemoveField(
            model_name="order",
            name="paid",
        ),
        migrations.RemoveField(
            model_name="order",
            name="updated",
        ),
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.CharField(
                default="USD",
                max_length=3,
                verbose_name="Валюта"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создан"),
                    ("paid", "Оплачен"),
                    ("failed", "Ошибка оплаты"),
                    ("canceled", "Отменен"),
                ],
                db_index=True,
                default="created",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                verbose_name="Дата обновления"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(
                help_text="Введите адрес доставки",
                max_length=250,
                verbose_name="Адрес"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="city",
            field=models.CharField(
                help_text="Введите город", max_length=100, verbose_name="Город"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(
                help_text="Введите email", max_length=254, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="first_name",
            field=models.CharField(
                help_text="Введите имя покупателя",
                max_length=50,
                verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_name",
            field=models.CharField(
                help_text="Введите фамилию покупателя",
                max_length=50,
                verbose_name="Фамилия",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="postal_code",
            field=models.CharField(
                help_text="Введите почтовый индекс",
                max_length=20,
                verbose_name="Почтовый индекс",
            ),
        ),
        migrations.AlterModelTable(
            name="order",
            table="orders",
        ),
    ]
